### PR TITLE
Enhancement: Solve to patterns and create partially scrambled cube

### PR DESCRIPTION
**Pull request by ansiwen**
As described in https://github.com/muodov/kociemba/issues/6

### CODE REVIEW

**Comment by muodov** [comment]
Lol, I was just about to comment on this. Basically, I would like to keep Python and C version in sync, so if you are still going to do this, can you consider changing C code as well? If not, it's not a problem, but I will have to do it myself before merging into master.

**Comment by ansiwen** [comment]
Oh, sorry. No, I basically wanted to make three isolated PRs because the stuff was not related. Are you sure you want to keep everything in sync? Sounds a bit like redundant work. Or do you need all features in a no-python environment? Else I would think it's good to reduce the redundancy only to the performance-critical parts, that is the solver.

**Comment by muodov** [comment]
I'd like to keep it in sync as long as possible, yes. I guess this change would be fairly easy to implement.
Besides, I noticed you were forcing python implementation in this new function, which makes it a way slower (on Raspberry Pi, for example, it is veery significant). That's why I thought it would be nice to have it implemented in C so that it is still fast and usable in both cases.

**Comment by ansiwen** [comment]
No, it still used the C solver, if I'm not mistaken. But I will have a look at it.

**Pull request closed without merging**
